#!/bin/sh /etc/rc.common

START=99
STOP=11

board_name() {
    [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

check_model() {
    local board=$(board_name)
    case "$board" in
        jp,tvbox|\
        panther,x2)
            /bin/ubus-examine.sh > /dev/null 2>&1 &
            ;;
        *)
            return 1
            ;;
    esac
}

start() {
    check_model
}

stop() {
    local board=$(board_name)
    case "$board" in
        jp,tvbox|\
        panther,x2)
            local pidcount=$(pgrep "ubus-examine" | wc -l)
            if [ "$pidcount" -eq 0 ]; then
                pidcount=$(pgrep "ubus-examine.sh" | wc -l)
            fi
            if [ "$pidcount" -gt 0 ]; then
                killall -9 ubus-examine ubus-examine.sh 2>/dev/null
            fi
            ;;
        *)
            return 1
            ;;
    esac
}

restart() {
    stop
    sleep 1
    start
}
