#!/bin/sh /etc/rc.common

START=99
STOP=11

board_name() {
    [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

check_model() {
    local board=$(board_name)
    case "$board" in
        jp,tvbox|\
        panther,x2)
            /sbin/ubus-status.sh > /dev/null 2>&1 &
            ;;
        *)
            return 1
            ;;
    esac
}

start() {
    check_model
}

stop() {
    local pidcount=$(pgrep "ubus-status" | wc -l)
    if [ "$pidcount" -eq 0 ]; then
        local pidcount=$(pgrep "ubus-status.sh" | wc -l)
    fi
    if [ "$pidcount" -gt 0 ]; then
        killall -9 ubus-status ubus-status.sh 2>/dev/null
    fi
}

restart() {
    stop
    start
}
